apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: {{.Values.namespace}}
  labels:
    app: frontend-pod
spec:
  containers:
    - name: frontend
      image: tvpow3r/frontend-app:52
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{.Values.namespace}}
spec:
  type: {{.Values.frontend.serviceType}}
  selector:
    app: frontend-pod
  ports:
   - port: 3000
     targetPort: 3000

