services:
  # I need to add the volume of my database here so is ran with the docker-compose

  # ============ DATABASE ============ Thank you warren for the comment lines :3
  db:
    image: mysql:8.4  # apparentely 8.4.24 does not support initdb.d
    container_name: mysql-server
    platform: linux/amd64 # Do I really need this just bc im on a mac?
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # This maps the local backup to the auto-import folder
      - ./backend/DB/backup.sql:/docker-entrypoint-initdb.d/init.sql
      # This is used so the data stays persistent even if the container is deleted
      - mysql_data:/var/lib/mysql
    healthcheck: # given that it takes some time to start up we need to add a healthcheck for the BE to run
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ============ NGINX SERVICE ============
  nginx:
    image: nginx:1.29-alpine #im not using a specified sub-version because I read this stays within the same major version
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  # ============ BACKEND ============
  backend:
    image: backend-app:${BACKEND_TAG:-6} #DONT USE LATEST
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysql-server:3306/${DB_NAME}
      - ROCKET_ADDRESS=0.0.0.0

#    ports:
#      - "8000:8000"
# YOU DONT NEED NETWORKS SETUP HERE IF YOU ARE USING DOCKER COMPOSE
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  # ============ FRONTEND ============
  frontend:
    image: frontend-app:6
#    ports:
#      - "3000:3000"    Need to see if this works without it


# Docker compose should be on the root folder of the machine to avoid moving .env files and being easier to manage
  # Add the DB volume here
  # Make a backup of my DB then add it as a volume here
volumes:
  mysql_data:
